# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
                ('food_selects', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RollRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('user_ip', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Activity')),
            ],
        ),
    ]
