# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 3, 30)),
        ),
    ]
