# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_activity_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='biller_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='biller_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rollrecord',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='create_date',
            field=models.DateField(default=datetime.date(2017, 4, 14)),
        ),
    ]
